spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # 熔断降级设定
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719


  redis:
    host: 192.168.56.10
  session:
    store-type: redis
  thymeleaf:
    cache: false


server:
  port: 20000
  servlet:
    session:
      timeout: 30m


# 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
