spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


    # 熔断降级设定
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  rabbitmq:
    host: 192.168.56.10
    #    username: niceseason
    #    password: mo19960729
    listener:
      simple:
        acknowledge-mode: manual

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
  session:
    store-type: redis

# 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.atguigu.gulimall: info

# 开启调用方熔断
feign:
  sentinel:
    enabled: true


