spring:
  redis:
    host: 192.168.56.10
    port: 6379
  application:
    name: gulimall-seckill
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.56.10
#    username: niceseason
#    password: mo19960729
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # 熔断降级设定
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

    # 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'




#    sentinel:
#      transport:
#        dashboard: localhost:8080
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#  #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

server:
  port: 15000


