server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.gulimall:3306/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
    template:
      mandatory: true

  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gulimall:8848

    # 熔断降级设定
    sentinel:
      transport:
        dashboard: sentinal-service.gulimall:8333
        port: 8719

  thymeleaf:
    cache: false
  redis:
    host: redis5-0-7.gulimall

  session:
    store-type: redis
  rabbitmq:
      host: redis5-0-7.gulimall
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


# 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

