server:
  port: 30000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719



  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10

# 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
