server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 熔断降级设定
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
  rabbitmq:
    host: 192.168.56.10
    listener:
      direct:
        acknowledge-mode: manual
    virtual-host: /

  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.56.10



# 信息审计模块的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'



#    host: 192.168.56.10
#      port: 5672
#      virtual-host: /
#      listener:
#        simple:
#          acknowledge-mode:
#            manual  rabbitmq:

    # 消息确认机制
    #publisher-confirms: true
    # 消息未能送到队列中时，返回一个信息
    #publisher-returns: true
    # 手动确认监听消息端的配置


  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual




mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu: debug