kind: Deployment
apiVersion: apps/v1
metadata:
  name: gulimall-seckill-server
  namespace: gulimall
  labels:
    app: gulimall-seckill-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-seckill-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gulimall-seckill-server
    spec:
      containers:
        - name: gulimall-seckill-server
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: gulimall-seckill-server
  namespace: gulimall
  labels:
    app: gulimall-seckill-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31009
  selector:
    app: gulimall-seckill-server
  type: NodePort
  sessionAffinity: None

